import "../styles/globals.css";
import type { AppProps } from "next/app";
import Head from "next/head";
import Header from "../components/Header";
import Footer from "../components/Footer";
import { EthereumProviders } from "../components/EthereumProviders";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Exquisite Graphics</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link rel="preconnect" href="https://fonts.gstatic.com"></link>
        <link
          href="https://fonts.google.com/specimen/IBM+Plex+Mono?category=Monospace"
          rel="stylesheet"
        ></link>
      </Head>
      {/* @ts-ignore */}
      <EthereumProviders>
        <Header />

        <div className="min-h-full flex flex-col items-center gap-2">
          <Component {...pageProps} />
          <Footer />
        </div>
      </EthereumProviders>
    </>
  );
}

export default MyApp;
